### ISSUE TITLE
Please improve connect function.

### ISSUE THREAD

**Issue by okletsgo** [chrishonselaar/ProtoPad#1]
I use Visual Studio and often restart iOS Simulator. Please add static server configuration in connection list. And How do you think about to use AvalonEdit or ScintillaNET instead of Actipro? It is a open source wpf library.

**Comment by chrishonselaar** [comment]
Do you mean that you would like ProtoPad to store manually added server IP's? Sounds like something we can do definitely, but please confirm. And is the UDP auto-discovery function not working for you? Please see the troubleshooting section in the readme.MD as well, that might help.
Please also note that if you restart the simulator, you do NOT need to reconnect from ProtoPad. You can simply start sending code again as soon as your simulator app is back up again.

Regarding Avalon/Scintilla - please see my [comments](http://forums.xamarin.com/discussion/comment/12696/#Comment_12696) in the forum thread. I am looking into creating an AvalonEdit-based alternative version. But I will also keep an ActiPro-based version going, simply because it offers so much more functionality and much better performance. By the way, if you want to contribute to ProtoPad (please do! I will be very grateful to have you join the contributors team - me&Bewolf2 currently), there is a solution regarding the ActiPro license.

**Comment by okletsgo** [comment]
Thank you. I fixed some bug and tried to compile it. (But I have no SyntaxEdit license.) So I commented. I like ProtoPad concept and believe, it will create more spare-time for everyone.

I had read readme.MD before running it. But It was not help me. In my case, need to alter DNS setting. So I suggest.

If you exchange WPF library, I can modify and commit it. I will happy if I can do commit.
